#!/usr/bin/env node
// Builds embed.ts into wallet-web/public/fxwallet.js: one classic script (no
// module, no CORS needed) that any dApp can include to list Ferminux Wallet
// under EIP-6963. The wallet serves it from both of its origins.
//
//   node shared/fxwallet/build-embed.mjs
//
// Uses the esbuild that wallet-web's Vite already installs.
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../../', import.meta.url));
const require = createRequire(`${root}wallet-web/package.json`);
const esbuild = require('esbuild');

const result = await esbuild.build({
  entryPoints: [`${root}shared/fxwallet/embed.ts`],
  bundle: true,
  format: 'iife',
  target: 'es2019',
  minify: true,
  legalComments: 'none',
  write: false,
});
const banner =
  '/* Ferminux Wallet — EIP-6963 announcement for any dApp. <script src="https://wallet.ferminux.net/fxwallet.js" async></script>\n' +
  '   GENERATED by shared/fxwallet/build-embed.mjs from shared/fxwallet/embed.ts. Do not edit by hand. */\n';
const out = `${root}wallet-web/public/fxwallet.js`;
writeFileSync(out, banner + result.outputFiles[0].text);
console.log(`wrote ${out} (${result.outputFiles[0].text.length} bytes)`);
