#!/usr/bin/env node
// Regenerates icon.ts: the EIP-6963 icon of Ferminux Wallet is the favicon from
// the brand build (brand/dist/favicon.svg), embedded as a data URI so the
// announcement never points a dApp at a network resource.
//
// brand/dist is build output (gitignored); every app ships a byte-identical
// copy in its public/ folder, so the wallet's copy is the fallback source.
//
//   node shared/fxwallet/gen-icon.mjs
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../../', import.meta.url));
const candidates = [`${root}brand/dist/favicon.svg`, `${root}wallet-web/public/favicon.svg`];
const source = candidates.find((p) => existsSync(p));
if (!source) throw new Error('favicon.svg not found (run brand/build.py first)');
const svg = readFileSync(source);
const uri = `data:image/svg+xml;base64,${svg.toString('base64')}`;
const out = `// GENERATED by shared/fxwallet/gen-icon.mjs from brand/dist/favicon.svg. Do not edit by hand.
// The Ferminux mark on its rounded square, as the EIP-6963 wallet icon.

export const FERMINUX_WALLET_ICON =
  '${uri}';
`;
writeFileSync(new URL('./icon.ts', import.meta.url), out);
console.log(`icon.ts written from ${source.slice(root.length)} (${svg.length} bytes)`);
