// Prebuild: reads ../deployments.3961.json (or ../deployments.json) written by the
// contracts deploy script and emits src/deployments.generated.ts. Without a deployments
// file the addresses are zero and the pages show a "registry not deployed yet" banner.
// VITE_REGISTRY / VITE_ESCROW / VITE_NFT env vars override whatever is generated (see src/config.ts).
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const candidates = [resolve(root, "../deployments.3961.json"), resolve(root, "../deployments.json")];
const ZERO = "0x0000000000000000000000000000000000000000";
// Addendum v3 contracts — same source file, optional keys. Zero address until the deploy script writes them.
const V3_KEYS = ["x402Vault", "accountFactory", "accountImpl", "streamPay", "arbiterPool", "identity8004", "reputation8004", "validation8004", "tokenFactory"];

let out = { chainId: 3961, registry: ZERO, escrow: ZERO, deployBlock: 0, nft: ZERO, nftDeployBlock: 0, v3DeployBlock: 0, source: "none" };
for (const k of V3_KEYS) out[k] = ZERO;
for (const file of candidates) {
  if (!existsSync(file)) continue;
  try {
    const j = JSON.parse(readFileSync(file, "utf8"));
    const isAddr = (a) => typeof a === "string" && /^0x[0-9a-fA-F]{40}$/.test(a);
    if (isAddr(j.registry) && isAddr(j.escrow)) {
      out = { chainId: Number(j.chainId || 3961), registry: j.registry, escrow: j.escrow, deployBlock: Number(j.deployBlock || 0), nft: isAddr(j.nft) ? j.nft : ZERO, nftDeployBlock: Number(j.nftDeployBlock || 0), v3DeployBlock: Number(j.v3DeployBlock || j.deployBlock || 0), source: file };
      for (const k of V3_KEYS) out[k] = isAddr(j[k]) ? j[k] : ZERO;
      break;
    }
    console.warn(`[gen-config] ${file} present but registry/escrow are not addresses; ignoring`);
  } catch (e) {
    console.warn(`[gen-config] could not parse ${file}: ${e.message}`);
  }
}

let ts = `// GENERATED by scripts/gen-config.mjs — do not edit. Source: ${out.source}
export const deployments = {
  chainId: ${out.chainId},
  registry: "${out.registry}",
  escrow: "${out.escrow}",
  deployBlock: ${out.deployBlock},
  nft: "${out.nft}",
  nftDeployBlock: ${out.nftDeployBlock},
  v3DeployBlock: ${out.v3DeployBlock},
  // Addendum v3 — Agent Economy (zero address = not deployed yet)
${V3_KEYS.map((k) => `  ${k}: "${out[k]}",`).join("\n")}
} as const;
`;
// Ferminux Citizens (FMXC): its own deploy file, written by DeployCitizens.s.sol, so the live
// deployments.3961.json is never rewritten. No file (not deployed yet) = zero address: the page shows the art
// and "Minting opens soon". The collection's name, symbol, base URL and tier table come from the single source
// of truth, ../nft/citizens/tiers.json (its token list stays out of the bundle).
let citizens = { address: ZERO, deployBlock: 0, source: "none" };
for (const file of [resolve(root, "../deployments-citizens.3961.json"), resolve(root, "../deployments-citizens.json")]) {
  if (!existsSync(file)) continue;
  try {
    const j = JSON.parse(readFileSync(file, "utf8"));
    if (/^0x[0-9a-fA-F]{40}$/.test(j.citizens ?? "") && Number(j.chainId ?? 3961) === 3961) { citizens = { address: j.citizens, deployBlock: Number(j.citizensDeployBlock || 0), source: file }; break; }
    console.warn(`[gen-config] ${file}: no citizens address for chain 3961; ignoring`);
  } catch (e) {
    console.warn(`[gen-config] could not parse ${file}: ${e.message}`);
  }
}
const tiersFile = resolve(root, "../nft/citizens/tiers.json");
const cc = existsSync(tiersFile) ? JSON.parse(readFileSync(tiersFile, "utf8")).collection : null;
const citizensMeta = cc
  ? { name: cc.name, symbol: cc.symbol, base: cc.base, tiers: cc.tiers.map((t) => ({ name: t.name, price: t.price })), series: Object.keys(cc.series ?? {}),
      // the curated standout ids (collection.showcase.square): the home page features them in this order
      showcase: (cc.showcase?.square ?? []).map(Number).filter((n) => Number.isInteger(n) && n > 0) }
  : { name: "Ferminux Citizens", symbol: "FMXC", base: "https://ferminux.net/nft/citizens", tiers: [], series: [], showcase: [] };
ts += `
// Ferminux Citizens — address from ${citizens.source === "none" ? "no deploy file (not deployed yet)" : citizens.source}
export const citizensDeployment = { address: "${citizens.address}", deployBlock: ${citizens.deployBlock} } as const;
// from ../nft/citizens/tiers.json: tier prices here are the configured launch prices; the page reads the live ones
export const citizensMeta = ${JSON.stringify(citizensMeta)} as const;
`;
writeFileSync(resolve(root, "src/deployments.generated.ts"), ts);
console.log(`[gen-config] registry=${out.registry} escrow=${out.escrow} nft=${out.nft} (${out.source === "none" ? "no deployments file — zero addresses" : out.source})`);
console.log(`[gen-config] citizens=${citizens.address === ZERO ? "— (not deployed)" : citizens.address} (${citizensMeta.name} / ${citizensMeta.symbol})`);
console.log(`[gen-config] v3: ${V3_KEYS.map((k) => `${k}=${out[k] === ZERO ? "—" : out[k]}`).join(" ")}`);

// ---- ABIs: copied verbatim from the compiled contracts (../contracts/abi/*.json) so the site can
// never drift from what is deployed (function/event/error shapes, indexed params, custom errors).
// Hand-written fragments used to live in src/abi.ts; they silently mis-decoded events (indexed
// params), missed the StreamPay getters and could not name custom errors.
const ABI_DIR = resolve(root, "../contracts/abi");
const ABI_FILES = {
  AgentRegistry: "AgentRegistry", ServiceEscrow: "ServiceEscrow", FerminuxAgents: "FerminuxAgents",
  X402Vault: "X402Vault", AgentAccount: "AgentAccount", AgentAccountFactory: "AgentAccountFactory", StreamPay: "StreamPay",
  ArbiterPool: "ArbiterPool", IdentityRegistry8004: "IdentityRegistry8004", ReputationRegistry8004: "ReputationRegistry8004",
  ValidationRegistry8004: "ValidationRegistry8004", AgentTokenFactory: "AgentTokenFactory", AgentToken: "AgentToken",
  FerminuxCitizens: "FerminuxCitizens",
};
const KEEP = new Set(["function", "event", "error"]);
const abiOut = [`// GENERATED by scripts/gen-config.mjs from ../contracts/abi/*.json — do not edit.`, `// Constructor/fallback entries are dropped; everything else is verbatim (JSON ABI, ethers v6 accepts it directly).`, `import type { JsonFragment } from "ethers";`, ``];
let missing = [];
for (const [name, file] of Object.entries(ABI_FILES)) {
  const f = resolve(ABI_DIR, `${file}.json`);
  if (!existsSync(f)) { missing.push(file); abiOut.push(`export const ${name}Abi: JsonFragment[] = [];`); continue; }
  const raw = JSON.parse(readFileSync(f, "utf8"));
  const list = (Array.isArray(raw) ? raw : raw.abi).filter((x) => KEEP.has(x.type)).map(({ type, name, inputs, outputs, stateMutability, anonymous }) => ({ type, name, inputs, ...(outputs ? { outputs } : {}), ...(stateMutability ? { stateMutability } : {}), ...(anonymous ? { anonymous } : {}) }));
  abiOut.push(`export const ${name}Abi: JsonFragment[] = ${JSON.stringify(list)};`);
}
writeFileSync(resolve(root, "src/abi.generated.ts"), abiOut.join("\n") + "\n");
console.log(`[gen-config] abi: ${Object.keys(ABI_FILES).length - missing.length} contracts from ${ABI_DIR}${missing.length ? ` (MISSING: ${missing.join(", ")} — empty ABI emitted)` : ""}`);
