#!/usr/bin/env bash
# Devnet keys: one random mnemonic, every role derived from it (BIP-44 index).
# Everything lands in .run/ (gitignored). These keys exist only for chain 39619
# on this machine; they hold no value anywhere and are never used on any other
# network. Attester keys are NOT made here: each sidecar makes its own with
# `fmx-validator keys new`, exactly as an operator would.
set -euo pipefail
HERE=$(cd "$(dirname "$0")" && pwd)
RUN="$HERE/.run"
mkdir -p "$RUN" && chmod 700 "$RUN"
if [ ! -s "$RUN/mnemonic" ]; then
  out=$(cast wallet new-mnemonic --words 12)
  awk '/^Phrase:/{getline; print; exit}' <<<"$out" > "$RUN/mnemonic"
fi
M=$(cat "$RUN/mnemonic")
[ "$(wc -w <<<"$M")" -eq 12 ] || { echo "bad mnemonic in $RUN/mnemonic" >&2; exit 1; }

pk()   { cast wallet private-key --mnemonic "$M" --mnemonic-index "$1"; }
addr() { cast wallet address --private-key "$1"; }

{
  echo "# generated by keys.sh: devnet chain 39619 only"
  echo "CHAIN_ID=39619"
  role() { local name=$1 idx=$2 k; k=$(pk "$idx"); echo "${name}_PK=$k"; echo "${name}=$(addr "$k")"; }
  role DEPLOYER 0
  role FUNDER 1
  role SIGNER1 2; role SIGNER2 3; role SIGNER3 4
  role OWNER1 5; role OWNER2 6; role OWNER3 7      # multisig owners = break-glass owners
  role REPORTER 8
  role OUTSIDER 9
  for i in $(seq 1 40); do role "SEATOWNER$i" $((9 + i)); done
} > "$RUN/devnet.env.tmp"
. "$RUN/devnet.env.tmp"
{
  cat "$RUN/devnet.env.tmp"
  # deployer nonce 0 = MinimalMultisig, nonce 1 = FMXRewardSink: the sink address is compiled into
  # the devnet node (params.FerminuxRewardSink), so it is fixed before the chain starts
  echo "MSIG=$(cast compute-address --nonce 0 "$DEPLOYER" | awk '{print $NF}')"
  echo "SINK=$(cast compute-address --nonce 1 "$DEPLOYER" | awk '{print $NF}')"
} > "$RUN/devnet.env"
rm -f "$RUN/devnet.env.tmp"
chmod 600 "$RUN/devnet.env" "$RUN/mnemonic"
grep -E '^(DEPLOYER|FUNDER|SIGNER[123]|OWNER[123]|MSIG|SINK)=' "$RUN/devnet.env"
